# Generated by Django 5.1.1 on 2024-09-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
