# Generated by Django 5.1.1 on 2024-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appoinment_app', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_appointments', models.JSONField()),
            ],
        ),
    ]
