# Generated by Django 5.1.1 on 2024-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdata',
            name='current_token',
            field=models.IntegerField(default=0),
        ),
    ]
